export const experience = [
  {
    role: "Cyber Security Intern",
    org: "Amalitech",
    period: "June 2026 – July 2026",
    skills: [
      "Linux",
      "Wireshark",
      "Network Security",
      "Vulnerability Assessment",
      "Nmap",
      "Penetration Testing Basics",
      "Bash Scripting",
    ],
    link: null,
  },
  {
    role: "Founder",
    org: "Aspire in Technology Africa",
    period: "June 2026 – Present",
    skills: [
      "Leadership",
      "Community Building",
      "Mentorship Program Design",
      "Nonprofit Operations",
      "Partnership Development",
      "Public Speaking",
      "Event Planning",
      "Email Marketing",
    ],
    link: "https://www.linkedin.com/company/aspire-in-technology-africa",
  },
  {
    role: "AI/ML Intern",
    org: "Plant Village",
    period: "May 2025 – Jun 2025",
    skills: [
      "Python",
      "Model Training",
      "Hugging Face",
      "Diffusion Models",
      "Technical Report Writing",
      "Data Preprocessing",
      "Image Classification",
      "PyTorch",
      "Model Evaluation",
      "Reinforcement Learning Fundamentals",
    ],
    link: null,
  },
];

export const leadership = [
  {
    role: "Resident Assistant (RA)",
    org: "Ashesi University",
    period: "Sep 2024 - Present",
  },
  {
    role: "Career Peer Advisor",
    org: "Ashesi University",
    period: "May 2024 - Present",
  },
  {
    role: "Secretary",
    org: "Women in Engineering (WiE)",
    period: "May 2025 - Present",
  },
  {
    role: "Programming and Writing Tutor",
    org: "Ashesi University",
    period: "Jan 2025 - Present",
  },
  {
    role: "Welfare Committee Secretary",
    org: "Ashesi Student Council",
    period: "Jan 2025 - Present",
  },
  {
    role: "General Secretary",
    org: "Ashesi Speech and Debate Association",
    period: "Aug 2024 - Present",
  },
  {
    role: "Volunteer Tutor",
    org: "Independent",
    period: "Sep 2021 - Present",
  },
];

export const projects = [
  {
    title: "100 Days of Hardware",
    period: "",
    description: "A daily hardware-building challenge to build hands-on embedded systems fluency, documented as a public portfolio.",
    techStack: ["Arduino", "C++", "Circuit Design"],
    category: "Hardware",
    link: null,
  },
  {
    title: "Cancer Research Paper",
    period: "",
    description: "A compartmental (SECR) mathematical model with optimal control to inform cancer prevention policy in Ghana.",
    techStack: ["MATLAB", "Optimal Control", "Epidemiological Modelling"],
    category: "Research",
    link: null,
  },
  {
    title: "Resume and Job Application Screening System",
    period: "",
    description: "A tool to automate screening and matching of resumes against job requirements.",
    techStack: ["Python", "NLP"],
    category: "AI/ML",
    link: null,
  },
  {
    title: "Polypropylene Research Paper (Material Science)",
    period: "Jan 2025 – May 2025",
    description: "An investigation into polypropylene's structure and relevance to sustainable development in Ghana.",
    techStack: ["Materials Science", "Research Writing"],
    category: "Research",
    link: null,
  },
  {
    title: "Cafeteria System in Java",
    period: "Oct 2024",
    description: "An inventory and transaction system for cafeteria operations, covering login, orders, and receipts.",
    techStack: ["Java", "OOP"],
    category: "Software",
    link: null,
  },
  {
    title: "Discrete Math Learning Tool (Logic Calculator)",
    period: "Oct 2024",
    description: "An interactive tool that evaluates logical expressions and generates truth tables to simplify discrete math concepts.",
    techStack: ["Python", "UI Logic"],
    category: "Software",
    link: null,
  },
  {
    title: "Predictive Model for Hydrogels",
    period: "Sep 2024 – Dec 2024",
    description: "A predictive model forecasting hydrogel water release rate based on soil type and PVA-to-Borax ratio.",
    techStack: ["Python", "Data Analysis"],
    category: "AI/ML",
    link: null,
  },
  {
    title: "Interactive Banking System Prototype",
    period: "Jul 2024 – Aug 2024",
    description: "A scalable banking system prototype with a modular, reusable codebase built for future database integration.",
    techStack: ["Python", "GUI Development"],
    category: "Software",
    link: null,
  },
  {
    title: "Space Shuttle Sensor System",
    period: "Mar 2024",
    description: "A model space shuttle measuring altitude, temperature, and pressure, with programmed payload release.",
    techStack: ["Embedded Systems", "Sensors"],
    category: "Hardware",
    link: null,
  },
  {
    title: "Farm Dialogue – Ashesi University",
    period: "Jan 2024 – Aug 2024",
    description: "Market research and stakeholder engagement to improve smallholder farmers' access to machinery in Ghana.",
    techStack: ["Market Research", "Stakeholder Engagement"],
    category: "Research",
    link: null,
  },
];

export const skillCategories = [
  {
    title: "Programming Languages",
    type: "logo",
    items: [
      { name: "Python", icon: "python/python-original" },
      { name: "Java", icon: "java/java-original" },
      { name: "C", icon: "c/c-original" },
      { name: "C++", icon: "cplusplus/cplusplus-original" },
      { name: "JavaScript", icon: "javascript/javascript-original" },
      { name: "TypeScript", icon: "typescript/typescript-original" },
      { name: "MATLAB", icon: "matlab/matlab-original" },
      { name: "SQL", icon: "mysql/mysql-original" },
      { name: "HTML5", icon: "html5/html5-original" },
      { name: "CSS3", icon: "css3/css3-original" },
      { name: "Bash", icon: "bash/bash-original" },
    ],
  },
  {
    title: "Frameworks & Libraries",
    type: "logo",
    items: [
      { name: "React", icon: "react/react-original" },
      { name: "Next.js", icon: "nextjs/nextjs-original" },
      { name: "Tailwind CSS", icon: "tailwindcss/tailwindcss-original" },
      { name: "Node.js", icon: "nodejs/nodejs-original" },
      { name: "PyTorch", icon: "pytorch/pytorch-original" },
      { name: "Hugging Face", icon: "huggingface/huggingface-original" },
      { name: "scikit-learn", icon: "scikitlearn/scikitlearn-original" },
      { name: "Pandas", icon: "pandas/pandas-original" },
      { name: "NumPy", icon: "numpy/numpy-original" },
    ],
  },
  {
    title: "Tools & Platforms",
    type: "logo",
    items: [
      { name: "Git", icon: "git/git-original" },
      { name: "GitHub", icon: "github/github-original" },
      { name: "Linux", icon: "linux/linux-original" },
      { name: "Supabase", icon: "supabase/supabase-original" },
      { name: "Jupyter Notebook", icon: "jupyter/jupyter-original" },
      { name: "Vercel", icon: "vercel/vercel-original" },
      { name: "Figma", icon: "figma/figma-original" },
    ],
  },
  {
    title: "Hardware Tools",
    type: "logo",
    items: [
      { name: "Arduino", icon: "arduino/arduino-original" },
      { name: "KiCad", icon: "kicad/kicad-original" },
    ],
  },
  {
    title: "Design & Productivity",
    type: "logo",
    items: [
      { name: "Canva", icon: "canva/canva-original" },
      { name: "Microsoft Office", icon: "microsoftsqlserver/microsoftsqlserver-plain" }, // placeholder, see note
      { name: "Google Workspace", icon: "google/google-original" },
    ],
  },
  {
    title: "Hardware & Embedded",
    type: "text",
    items: [
      "Verilog",
      "VHDL",
      "Proteus",
      "Circuit Design / PCB Design",
      "Sensors & Actuators",
      "Embedded C",
      "Microcontroller Programming",
    ],
  },
  {
    title: "AI/ML & Data",
    type: "text",
    items: [
      "Machine Learning Fundamentals",
      "Deep Learning",
      "Model Training & Evaluation",
      "Data Preprocessing",
      "Image Classification",
      "Reinforcement Learning",
      "Diffusion Models",
      "NLP Basics",
      "Data Analysis / Visualization",
      "Statistical Modelling",
    ],
  },
  {
    title: "Math & Research Methods",
    type: "text",
    items: [
      "Mathematical Modelling",
      "Optimal Control Theory",
      "Differential Equations",
      "Optimization",
      "Technical Report Writing",
      "Academic Research & Literature Review",
    ],
  },
  {
    title: "Design Fundamentals & Languages",
    type: "text",
    items: ["UI/UX Design Fundamentals", "Conversational French"],
  },
];
export const stats = [
  { label: "Experience", value: "4+ years coding with projects" },
  { label: "Research", value: "3+ research projects" },
  { label: "Hardware", value: "5+ hardware builds" },
  { label: "Skills", value: "Python, MATLAB, C, React" },
  { label: "Interested Roles", value: "Research · Full Stack · Software Development · Embedded Systems · AI/ML" },
];